services:
  web-app:
    build:
      context: ./web-app
    image: web-app
    ports:
      - "8001:8000"
    depends_on:
      pocketbase-db:
        condition: service_healthy
    restart: unless-stopped

  terminal-app:
    build:
      context: ./terminal-app
    image: terminal-app
    env_file:
      - ./.env
    environment:
      - PB_BASE_URL=http://pocketbase-db:8080
    ports:
      - "22:22"
    volumes:
      - ./.ssh:/app/.ssh:ro
    depends_on:
      pocketbase-db:
        condition: service_healthy
    restart: unless-stopped

  pocketbase-db:
    build:
      context: ./pocketbase
    image: pocketbase-db
    env_file:
      - ./.env
    ports:
      - "8080:8080"
    volumes:
      - ./pocketbase/pb_data:/pocketbase/pb_data
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/api/health"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  pocketbase-db_data:
    name: pocketbase-db_data